[package]
name = "mergechannels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mergechannels"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.5.0"
ndarray = "0.16.1"
numpy = "0.24.0"
pyo3 = "0.24.1"
